### ISSUE TITLE
Error: Unsupported role: tool

### ISSUE THREAD

**Issue by waltershewmake** [sgomez/ollama-ai-provider#12]
**Describe the bug**
When attempting to use the `maxToolRoundtrips` parameter in the `generateText` method from the `ai` package, I get the following error: `Unsupported role: tool`. I tracked the error down to this package, as it doesn't occur with the openai package from `@ai-sdk/openai`. 

**To Reproduce**
1. Clone my [example repo](https://github.com/waltershewmake/vercel-ai-tool-error)
2. Install the dependencies with `pnpm install`
3. Run the sample code with `pnpm tsx index.ts`

**Comment by sgomez** [comment]
Please, try again with the new release. Thanks

**Comment by sgomez** [comment]
@waltershewmake I can confirm that the last version (0.11.0) solves the issue. Thanks for the report.
