### ISSUE TITLE
Incompatible with newest version of the ai SDK

### ISSUE THREAD

**Issue by treyhuffine** [sgomez/ollama-ai-provider#29]
/node_modules/ollama-ai-provider/node_modules/@ai-sdk/provider-utils/dist/index.mjs
Attempted import error: 'LoadSettingError' is not exported from '@ai-sdk/provider' (imported as 'LoadSettingError').

Import trace for requested module:
./node_modules/ollama-ai-provider/node_modules/@ai-sdk/provider-utils/dist/index.mjs
./node_modules/ollama-ai-provider/dist/index.mjs
./src/services/server/ai/index.ts
./src/app/api/chat/route.ts

**Comment by sgomez** [comment]
Sorry, because I didn't see the notification of this issue, although it must have been resolved shortly after. I am updating it as I have time on weekends. I also just released another new release to support the latest changes. If it doesn't work please open another issue.
