### ISSUE TITLE
Accumulation and logging of previous AI responses using the Vercel AI SDK

### ISSUE THREAD

**Issue by manishrc** [sgomez/ollama-ai-provider#8]
**Describe the bug**
When using `streamText` with `ollama` and Vercel AI SDK, there seems to be an issue where previous messages are logged, instead of only the generated response.

I've tested this with mistral and gemma2, with the same result. The issues seems to go away when using `openai`, hence reporting it here instead of Vercel's SDK.

**To Reproduce**

```
npm install ai ollama-ai-provider
```

```javascript
import { ollama } from 'ollama-ai-provider';
import { generateText } from 'ai';

(async () => {
  const { text } = await generateText({
    model: ollama('mistral'),
    system: 'You are a helpful assistant.',
    messages: [
      { role: 'user', content: 'What is 1+1?' },
      { role: 'assistant', content: '2' },
      { role: 'user', content: 'What is 2+2?' },
      { role: 'assistant', content: '4' },
      { role: 'user', content: 'What is 3+3?' },
    ],
  });

  console.log(text);
})();
```

**Result**

EXPECTED:

```shell
6
```

ACTUAL:

```shell
2
4
 6
```

**Desktop (please complete the following information):**
 - OS: MacOS 14.5 (23F79)
 - Browser: N/A
 - Node: v20.11.0
 - ollama-ai-provider: 0.9.0
 - vercel ai SDK: 3.2.15

This issue makes it difficult to build terminal-based chat interfaces, as previous messages are being repeatedly shown:

![CleanShot 2024-06-30 at 8  30 38@2x](https://github.com/sgomez/ollama-ai-provider/assets/324068/deabfd76-c1f8-4675-9020-f6cc049029f9)

**Comment by sgomez** [comment]
Thanks @manishrc. I left a console.error in the code and it was printing the intermediate responses. I released the version 0.9.1 with the fix.
